"""
drop_bad_segments.py

Backfill noisy-segment dropping and QC plotting for already processed EEG segment
files (e.g., generated by older create_eeg_ds.py runs before bad-segment drop).

This script does NOT read EDF files and does NOT run filtering/normalization.
It operates directly on saved segment arrays: <patient>_spikes_<l>-<h>Hz.npy

Outputs:
- Cleaned segment .npy files (same naming convention)
- Per-patient JSON report under output_dir/logs/
- QC plot for kept segments under qc/
- QC plot for dropped segments under qc/dropped/
"""

import argparse
import json
import re
from pathlib import Path

import numpy as np
from tqdm import tqdm

from create_eeg_ds import drop_noisy_segments, quality_control_plot


DEFAULT_CHANNELS = [
    "Fp1", "Fp2", "F9", "F10", "F7", "F3", "Fz", "F4", "F8",
    "T7", "C3", "Cz", "C4", "T8",
    "P7", "P3", "Pz", "P4", "P8",
    "O1", "O2",
]


def _resolve_channel_names(n_channels, channels_csv):
    if channels_csv:
        names = [ch.strip() for ch in channels_csv.split(",") if ch.strip()]
    else:
        names = list(DEFAULT_CHANNELS)

    if len(names) < n_channels:
        names.extend([f"Ch{i + 1}" for i in range(len(names), n_channels)])
    elif len(names) > n_channels:
        names = names[:n_channels]

    return names


def _find_patient_band_files(input_dir):
    pattern = re.compile(r"^(?P<pid>.+)_spikes_(?P<lo>\d+)-(?P<hi>\d+)Hz\.npy$")
    grouped = {}

    for path in sorted(Path(input_dir).glob("*_spikes_*Hz.npy")):
        match = pattern.match(path.name)
        if not match:
            continue
        pid = match.group("pid")
        lo = int(match.group("lo"))
        hi = int(match.group("hi"))
        grouped.setdefault(pid, []).append((lo, hi, path))

    for pid in grouped:
        grouped[pid] = sorted(grouped[pid], key=lambda x: x[0])

    return grouped


def _load_timestamps(patient_id, events_dir, n_segments):
    if events_dir is None:
        return np.arange(n_segments, dtype=float), "synthetic_index"

    events_path = Path(events_dir) / f"{patient_id}_events.json"
    if not events_path.exists():
        return np.arange(n_segments, dtype=float), "synthetic_index_missing_events"

    with open(events_path, "r") as f:
        events_data = json.load(f)

    spikes = np.array(events_data.get("spikes", []), dtype=float)

    if len(spikes) == n_segments:
        return spikes, "events_json_exact"

    if len(spikes) > n_segments:
        # Older preprocessing may have skipped out-of-bounds segments.
        return spikes[:n_segments], "events_json_truncated"

    return np.arange(n_segments, dtype=float), "synthetic_index_events_too_short"


def process_patient(
    patient_id,
    band_files,
    output_dir,
    events_dir,
    qc_dir,
    channels_csv,
    noise_cfg,
    write_qc,
):
    tqdm.write("\n================================")
    tqdm.write(f"Processing patient {patient_id}...")

    freq_bands = [(lo, hi) for (lo, hi, _) in band_files]
    segments_bands = [np.load(path).astype(np.float32, copy=False) for (_, _, path) in band_files]

    if len(segments_bands) == 0:
        tqdm.write("No bands found, skipping.")
        return None

    n_segments = segments_bands[0].shape[0]
    n_channels = segments_bands[0].shape[1]
    channels_to_keep = _resolve_channel_names(n_channels=n_channels, channels_csv=channels_csv)

    inconsistent = [sb.shape[0] != n_segments for sb in segments_bands]
    if any(inconsistent):
        tqdm.write(f"Warning: inconsistent segment counts across bands for {patient_id}, skipping.")
        return None

    timestamps, timestamp_source = _load_timestamps(patient_id, events_dir, n_segments)

    valid_mask = np.ones(n_channels, dtype=bool)

    if write_qc:
        segments_bands_pre = [sb.copy() for sb in segments_bands]
        timestamps_pre = timestamps.copy()
    else:
        segments_bands_pre = None
        timestamps_pre = None

    cleaned_bands, kept_timestamps, noise_qc = drop_noisy_segments(
        segments_bands=segments_bands,
        timestamps=timestamps,
        valid_mask=valid_mask,
        noise_cfg=noise_cfg,
    )

    kept_mask = np.array(noise_qc["detail"]["keep_mask"], dtype=bool)
    dropped_mask = np.array(noise_qc["detail"]["drop_mask"], dtype=bool)
    bad_ptp_mask = np.array(noise_qc["detail"]["bad_ptp"], dtype=bool)
    bad_flat_mask = np.array(noise_qc["detail"]["bad_flat"], dtype=bool)
    bad_extreme_mask = np.array(noise_qc["detail"]["bad_extreme"], dtype=bool)
    bad_hf_mask = np.array(noise_qc["detail"]["bad_hf"], dtype=bool)

    output_dir.mkdir(parents=True, exist_ok=True)
    for (lo, hi, _), band_arr in zip(band_files, cleaned_bands):
        out_path = output_dir / f"{patient_id}_spikes_{lo}-{hi}Hz.npy"
        np.save(out_path, band_arr)
        tqdm.write(f"Saved cleaned band {lo}-{hi} Hz: {band_arr.shape} -> {out_path}")

    logs_dir = output_dir / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    report = {
        "patient_id": patient_id,
        "freq_bands": freq_bands,
        "input_segment_count": int(n_segments),
        "final_kept_count": int(noise_qc["kept"]),
        "noisy_dropped_count": int(noise_qc["dropped"]),
        "timestamp_source": timestamp_source,
        "noise_cfg": noise_cfg,
        "summary": {
            "noise_drop_fraction": float(noise_qc["drop_fraction"]),
            "reason_counts": noise_qc["reason_counts"],
        },
        "noisy_dropped": [
            {
                "segment_index": int(i),
                "timestamp_sec": float(timestamps[i]),
                "reasons": [
                    reason
                    for reason, cond in [
                        ("ptp", bool(bad_ptp_mask[i])),
                        ("flat", bool(bad_flat_mask[i])),
                        ("extreme_samples", bool(bad_extreme_mask[i])),
                        ("hf_ratio", bool(bad_hf_mask[i])),
                    ]
                    if cond
                ],
                "metrics": {
                    "ptp_z": float(noise_qc["detail"]["ptp_z"][i]),
                    "flat_frac": float(noise_qc["detail"]["flat_frac"][i]),
                    "extreme_frac": float(noise_qc["detail"]["extreme_frac"][i]),
                    "hf_ratio_z": float(noise_qc["detail"]["hf_ratio_z"][i]),
                },
            }
            for i in range(n_segments)
            if dropped_mask[i]
        ],
        "kept_segments": [
            {
                "segment_index": int(i),
                "timestamp_sec": float(timestamps[i]),
            }
            for i in range(n_segments)
            if kept_mask[i]
        ],
    }

    report_path = logs_dir / f"{patient_id}_segment_rejection_report.json"
    with open(report_path, "w") as f:
        json.dump(report, f, indent=2)
    tqdm.write(f"Saved segment rejection report: {report_path}")

    if write_qc and qc_dir is not None:
        qc_dir.mkdir(parents=True, exist_ok=True)
        dropped_qc_dir = qc_dir / "dropped"
        dropped_qc_dir.mkdir(parents=True, exist_ok=True)

        valid_qc_path = qc_dir / f"quality_control_{patient_id}.png"
        dropped_qc_path = dropped_qc_dir / f"quality_control_dropped_{patient_id}.png"

        tqdm.write(f"Generating QC for kept segments: {valid_qc_path}")
        quality_control_plot(
            segments_bands=cleaned_bands,
            timestamps=kept_timestamps,
            channels_to_keep=channels_to_keep,
            patient_id=patient_id,
            freq_bands=freq_bands,
            output_path=str(valid_qc_path),
        )

        if np.sum(dropped_mask) > 0:
            dropped_segments_bands = [sb[dropped_mask] for sb in segments_bands_pre]
            dropped_timestamps = timestamps_pre[dropped_mask]
            tqdm.write(f"Generating QC for dropped segments: {dropped_qc_path}")
            quality_control_plot(
                segments_bands=dropped_segments_bands,
                timestamps=dropped_timestamps,
                channels_to_keep=channels_to_keep,
                patient_id=f"{patient_id} (dropped)",
                freq_bands=freq_bands,
                output_path=str(dropped_qc_path),
            )
        else:
            tqdm.write("No dropped segments for this patient, skipped dropped QC plot.")

    return {
        "patient_id": patient_id,
        "drop_fraction": float(noise_qc["drop_fraction"]),
        "input_segment_count": int(n_segments),
        "noisy_dropped_count": int(noise_qc["dropped"]),
        "final_kept_count": int(noise_qc["kept"]),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Drop noisy segments from already processed EEG spike .npy files and generate QC."
    )
    parser.add_argument(
        "--input_dir",
        type=str,
        required=True,
        help="Directory containing old processed files: <patient>_spikes_<l>-<h>Hz.npy",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        required=False,
        default=None,
        help="Directory to save cleaned files. Default: input_dir (in-place overwrite).",
    )
    parser.add_argument(
        "--events_dir",
        type=str,
        required=False,
        default=None,
        help="Optional directory with <patient>_events.json for timestamps in QC/report.",
    )
    parser.add_argument(
        "--qc_dir",
        type=str,
        required=False,
        default=None,
        help="Directory for QC outputs. Default: <output_dir>/qc",
    )
    parser.add_argument(
        "--channels",
        type=str,
        required=False,
        default=None,
        help="Optional comma-separated channel labels for QC y-axis.",
    )
    parser.add_argument(
        "--write_qc",
        action=argparse.BooleanOptionalAction,
        default=True,
        help="Write QC plots for kept and dropped segments (default: True).",
    )
    parser.add_argument(
        "--noise_ptp_z_thresh",
        type=float,
        default=6.0,
        help="Robust z-score threshold on epoch median peak-to-peak amplitude.",
    )
    parser.add_argument(
        "--noise_flat_ptp_thresh",
        type=float,
        default=0.05,
        help="Segment/channel considered flat if peak-to-peak is below this (normalized units).",
    )
    parser.add_argument(
        "--noise_flat_channel_frac_thresh",
        type=float,
        default=0.3,
        help="Drop epoch if this fraction of channels are flat.",
    )
    parser.add_argument(
        "--noise_abs_z_thresh",
        type=float,
        default=10.0,
        help="Absolute robust-z threshold for extreme samples.",
    )
    parser.add_argument(
        "--noise_abs_z_frac_thresh",
        type=float,
        default=0.01,
        help="Drop epoch if fraction of extreme samples exceeds this threshold.",
    )
    parser.add_argument(
        "--noise_hf_ratio_z_thresh",
        type=float,
        default=6.0,
        help="Robust z-score threshold on high-frequency contamination ratio.",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir) if args.output_dir is not None else input_dir
    qc_dir = Path(args.qc_dir) if args.qc_dir is not None else (output_dir / "qc")

    tqdm.write("Running drop_bad_segments.py with settings:")
    for k, v in vars(args).items():
        tqdm.write(f"  {k}: {v}")

    grouped = _find_patient_band_files(input_dir)
    tqdm.write(f"Found {len(grouped)} patients with processed spike files in {input_dir}")

    if len(grouped) == 0:
        tqdm.write("No matching files found. Expected pattern: <patient>_spikes_<l>-<h>Hz.npy")
        return

    noise_cfg = {
        "ptp_z_thresh": args.noise_ptp_z_thresh,
        "flat_ptp_thresh": args.noise_flat_ptp_thresh,
        "flat_channel_frac_thresh": args.noise_flat_channel_frac_thresh,
        "abs_z_thresh": args.noise_abs_z_thresh,
        "abs_z_frac_thresh": args.noise_abs_z_frac_thresh,
        "hf_ratio_z_thresh": args.noise_hf_ratio_z_thresh,
    }

    dataset_drop_summary = []
    warning_drop_threshold = 0.25

    for patient_id, band_files in tqdm(
        grouped.items(),
        total=len(grouped),
        desc="Patients",
        unit="patient",
    ):
        patient_result = process_patient(
            patient_id=patient_id,
            band_files=band_files,
            output_dir=output_dir,
            events_dir=args.events_dir,
            qc_dir=qc_dir,
            channels_csv=args.channels,
            noise_cfg=noise_cfg,
            write_qc=args.write_qc,
        )
        if patient_result is not None:
            dataset_drop_summary.append(patient_result)

    logs_dir = output_dir / "logs"
    logs_dir.mkdir(parents=True, exist_ok=True)

    dataset_summary_path = logs_dir / "dataset_drop_summary.json"
    dataset_summary_payload = {
        "warning_drop_threshold": warning_drop_threshold,
        "n_subjects": len(dataset_drop_summary),
        "subjects": sorted(dataset_drop_summary, key=lambda x: x["patient_id"]),
    }
    with open(dataset_summary_path, "w") as f:
        json.dump(dataset_summary_payload, f, indent=2)
    tqdm.write(f"Saved dataset-level drop summary: {dataset_summary_path}")

    warning_subjects = [
        s for s in dataset_drop_summary if s.get("drop_fraction", 0.0) > warning_drop_threshold
    ]
    warning_path = logs_dir / "warning_drop_ratio.txt"
    with open(warning_path, "w") as f:
        f.write(f"Subjects with drop_fraction > {warning_drop_threshold:.2f}\n")
        if not warning_subjects:
            f.write("None\n")
        else:
            for s in sorted(warning_subjects, key=lambda x: x["patient_id"]):
                f.write(f"{s['patient_id']}\t{s['drop_fraction']:.4f}\n")
    tqdm.write(f"Saved warning drop-ratio file: {warning_path}")

    tqdm.write("\nDone.")


if __name__ == "__main__":
    main()
